### ISSUE TITLE
can't open .webp files

### ISSUE THREAD

**Issue by Landius** [udaken/ifgflsdk#3]
I tried .ico, .icns, .psd, .tga, the plug-in works fine.
And when I tried to open .webp file, the program noticed `"unknown type"`.
But the .webp format is supported according to form in `readme.md`...

thanks for developing such a useful plug-in!

**Comment by udaken** [comment]
Sorry, This is a bug in README.md.
GFLSDK does not support WebP.

**Comment by udaken** [comment]
Fix README.md.
thx @Landius
